# Generated by Django 5.0.6 on 2025-01-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
