# Generated by Django 5.0.6 on 2025-01-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_delete_featuredproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_desc', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cart/images')),
            ],
        ),
    ]
