# Generated by Django 5.0.6 on 2025-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0004_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('f_desc', models.CharField(max_length=60)),
                ('f_price', models.IntegerField(default=0)),
                ('f_image', models.ImageField(default='', upload_to='cart/images')),
            ],
        ),
    ]
