# Generated by Django 5.0.6 on 2025-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_name', models.CharField(max_length=50)),
                ('n_desc', models.CharField(max_length=60)),
                ('n_price', models.IntegerField(default=0)),
                ('n_image', models.ImageField(default='', upload_to='cart/newarr')),
            ],
        ),
    ]
