# Generated by Django 5.0.6 on 2025-01-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_clothes_delete_featuredproducts_delete_features_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothes',
            new_name='Products',
        ),
    ]
