# Generated by Django 5.0.6 on 2025-01-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_rename_clothes_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='cart/images'),
        ),
    ]
