# Generated by Django 5.0.6 on 2025-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
