# Generated by Django 5.0.6 on 2025-01-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
